/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfsPartFeats.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=0.0001 useLocallyPred=false maxFails=5 partitionSize=5 restrictPartitionSizeIncrease=false
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfsPartFeats.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=0.001 useLocallyPred=false maxFails=5 partitionSize=5 restrictPartitionSizeIncrease=false
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfsPartFeats.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=0.01 useLocallyPred=false maxFails=5 partitionSize=5 restrictPartitionSizeIncrease=false
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfsPartFeats.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=0.1 useLocallyPred=false maxFails=5 partitionSize=5 restrictPartitionSizeIncrease=false
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfsPartFeats.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 partitionSize=5 restrictPartitionSizeIncrease=false

# History
#java -Xmx3800m  weka.attributeSelection.CfsSubsetEval -s "weka.attributeSelection.BestFirst -D 1 -N 5 -S 0" -L -P 1 -E 1 -i /home/raul/Datasets/Medium/covtype-discrete.arff &> /home/raul/Desktop/SparkCFS/project-files/src/test/weka.log
# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/tmp.jar hdfs://master:8020/datasets/HIGGS.arff
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfs.jar hdfs://master:8020/datasets/ECBDL14_train-discretized_{0}perc.parquet useLocallyPred=true useGA=true useNFeatsForPopulationSize=true optIslandPopulationSize=0
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfs.jar  hdfs://master:8020/datasets/ECBDL14_traindiscretized0-629.parquet hdfs://master:8020/datasets/ECBDL14_train-discretized-columns.parquet hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/QuantileDiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_train.arff