# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/temp.jar hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet "94,162,163,167,168,169,170,253,254,257,258,270,433,434,437,450" 5
# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/temp.jar hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet "94,162,163,165,167,168,169,170,253,254,257,258,262,270,433,434,437,438,450" 10
# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/temp.jar hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet "94,162,163,165,167,168,169,170,253,254,256,257,258,270,433,434,437,438,450" 15
# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/temp.jar hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet "94,162,163,165,167,168,169,170,253,254,257,258,262,270,433,434,437,438,450" 20
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=5
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=10
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=15
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=20
/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=25
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp-nocache.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=0.05 useLocallyPred=false maxFails=5 initialPartitionSize=5
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp-nocache.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized_05perc.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=5
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=10 restrictPartitionSizeIncrease=false
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=15 restrictPartitionSizeIncrease=false
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=20 restrictPartitionSizeIncrease=false
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/temp.jar  hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet resultsPath=/root/results/ sampleSize=1.0 useLocallyPred=false maxFails=5 initialPartitionSize=25 restrictPartitionSizeIncrease=false

# History
#java -Xmx3800m  weka.attributeSelection.CfsSubsetEval -s "weka.attributeSelection.BestFirst -D 1 -N 5 -S 0" -L -P 1 -E 1 -i /home/raul/Datasets/Medium/covtype-discrete.arff &> /home/raul/Desktop/SparkCFS/project-files/src/test/weka.log
# /opt/spark/bin/spark-submit --class rauljosepalma.sparkmltools.Main /root/tmp.jar hdfs://master:8020/datasets/HIGGS.arff
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfs.jar hdfs://master:8020/datasets/ECBDL14_train-discretized_{0}perc.parquet useLocallyPred=true useGA=true useNFeatsForPopulationSize=true optIslandPopulationSize=0
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/cfs.jar  hdfs://master:8020/datasets/ECBDL14_traindiscretized0-629.parquet hdfs://master:8020/datasets/ECBDL14_train-discretized-columns.parquet hdfs://master:8020/datasets/ECBDL14_train-discretized.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/QuantileDiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_train.arff