/opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main /root/QuantileDiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_train.arff
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_10perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_20perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_30perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_40perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_50perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_60perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_70perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_80perc.parquet
# /opt/spark/bin/spark-submit --class org.apache.spark.ml.feature.Main --packages sramirez:spark-MDLP-discretization:1.2.1 /root/MLDPdiscretizer.jar  hdfs://master:8020/datasets/ECBDL14_90perc.parquet