%======================
% PATHS RELATED DATA
%======================
results.pathd.results_folder='NFkB';    
results.pathd.short_name='NFkB';        

%======================
% MODEL RELATED DATA
%======================
inputs.model.input_model_type='charmodelC'; 
inputs.ivpsol.ivpsolver='cvodes';
inputs.ivpsol.senssolver='cvodes';

inputs.model.n_st=15;                                   
inputs.model.n_par=29;                                  
inputs.model.n_stimulus=1;                              
inputs.model.st_names=char('IKKn','IKKa','IKKi','IKKaIkBa','IKKaIkBaNFkB','NFkB','NFkBn','A20','A20t',...
                           'IkBa','IkBan','IkBat','IkBaNFkB','IkBanNFkBn','cgent');         
                       
inputs.model.par_names=char('a1','a2','t1','a3','t2','c1a','c2a','c3a','c4a','c5a',...
                            'c6a','c1','c2','c3','c4','c5','k1','k2','k3','kprod','kdeg',...
                            'kv','i1','e2a','i1a','e1a','c1c','c2c','c3c');
                                                        
inputs.model.stimulus_names=char('Tr');
                                                        
inputs.model.eqns=char('dIKKn=kprod-kdeg*IKKn-Tr*k1*IKKn',... 
                       'dIKKa=Tr*k1*IKKn-k3*IKKa-Tr*k2*IKKa*A20-kdeg*IKKa-a2*IKKa*IkBa+t1*IKKaIkBa-a3*IKKa*IkBaNFkB+t2*IKKaIkBaNFkB',...
                       'dIKKi=k3*IKKa+Tr*k2*IKKa*A20-kdeg*IKKi',...
                       'dIKKaIkBa=a2*IKKa*IkBa-t1*IKKaIkBa',...
                       'dIKKaIkBaNFkB=a3*IKKa*IkBaNFkB-t2*IKKaIkBaNFkB',...
                       'dNFkB=c6a*IkBaNFkB-a1*NFkB*IkBa+t2*IKKaIkBaNFkB-i1*NFkB',...
                       'dNFkBn=i1*kv*NFkB-a1*IkBan*NFkBn',...
                       'dA20=c4*A20t-c5*A20',...
                       'dA20t=c2+c1*NFkBn-c3*A20t',...
                       'dIkBa=-a2*IKKa*IkBa-a1*IkBa*NFkB+c4a*IkBat-c5a*IkBa-i1a*IkBa+e1a*IkBan',...
                       'dIkBan=-a1*IkBan*NFkBn+i1a*kv*IkBa-e1a*kv*IkBan',...
                       'dIkBat=c2a+c1a*NFkBn-c3a*IkBat',...
                       'dIkBaNFkB=a1*IkBa*NFkB-c6a*IkBaNFkB-a3*IKKa*IkBaNFkB+e2a*IkBanNFkBn',...
                       'dIkBanNFkBn=a1*IkBan*NFkBn-e2a*kv*IkBanNFkBn',...
                       'dcgent=c2c+c1c*NFkBn-c3c*cgent');
                  
inputs.model.par=[0.5 0.2 0.1 1 0.1 5e-7 0 0.0004 0.5 ...
                 0.0001 0.00002 5e-7 0 0.0004 0.5 0.0003 ...
                 0.0025 0.1 0.0015 0.000025 0.000125 5 ...
                 0.0025 0.01 0.001 0.0005 5e-7 0 0.0004];

